#!/usr/bin/env node

/**
 * Environment Setup Script
 * 
 * This script helps you configure your .env file with your actual Discourse instance details.
 */

const fs = require('fs');
const readline = require('readline');

// Colors for console output
const colors = {
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  reset: '\x1b[0m',
  bold: '\x1b[1m'
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function logStep(step) {
  log(`\n${colors.bold}${step}${colors.reset}`);
}

function logSuccess(message) {
  log(`✅ ${message}`, 'green');
}

function logError(message) {
  log(`❌ ${message}`, 'red');
}

function logWarning(message) {
  log(`⚠️  ${message}`, 'yellow');
}

function logInfo(message) {
  log(`ℹ️  ${message}`, 'blue');
}

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setupEnvironment() {
  log(`${colors.bold}🔧 Discourse Environment Setup${colors.reset}`);
  log('This script will help you configure your .env file with your Discourse instance details.');
  log('');

  try {
    // Check if .env already exists and has content
    const envPath = '.env';
    let existingContent = '';
    
    if (fs.existsSync(envPath)) {
      existingContent = fs.readFileSync(envPath, 'utf8');
      if (existingContent.trim()) {
        logWarning('A .env file already exists with content.');
        const overwrite = await question('Do you want to overwrite it? (y/N): ');
        if (overwrite.toLowerCase() !== 'y' && overwrite.toLowerCase() !== 'yes') {
          logInfo('Setup cancelled. Your existing .env file was preserved.');
          rl.close();
          return;
        }
      }
    }

    logStep('📝 Discourse Instance Configuration');
    
    // Get Discourse URL
    logInfo('Enter your Discourse instance URL:');
    logInfo('Example: https://discourse.example.com');
    const discourseUrl = await question('Discourse URL: ');
    
    if (!discourseUrl || discourseUrl === 'https://your-discourse-instance.com') {
      logError('Please provide a valid Discourse URL.');
      rl.close();
      return;
    }

    // Validate URL format
    try {
      new URL(discourseUrl);
    } catch {
      logError('Invalid URL format. Please provide a valid URL starting with http:// or https://');
      rl.close();
      return;
    }

    // Note about User API Keys
    logStep('🔑 Authentication');
    logInfo('This app uses User API Keys for authentication.');
    logInfo('Users will authorize the app through the Discourse web interface.');
    logInfo('No admin API credentials are needed.');
    logInfo('');

    // Security settings
    logStep('🔒 Security Settings');
    logInfo('Configuring security settings...');
    
    const enableHttpsOnly = await question('Enable HTTPS only? (Y/n): ');
    const enableRateLimiting = await question('Enable rate limiting? (Y/n): ');
    const enableDebugMode = await question('Enable debug mode for development? (y/N): ');

    // Generate .env content
    const envContent = `# Discourse API Configuration
# Generated by setup script - ${new Date().toISOString()}

# Your Discourse instance URL (must be HTTPS in production)
EXPO_PUBLIC_DISCOURSE_URL=${discourseUrl}

# Authentication: This app uses User API Keys
# Users authorize the app through the Discourse web interface
# No admin API credentials are needed

# Security Settings
EXPO_PUBLIC_ENABLE_HTTPS_ONLY=${enableHttpsOnly.toLowerCase() !== 'n' ? 'true' : 'false'}
EXPO_PUBLIC_ENABLE_CERT_PINNING=false
EXPO_PUBLIC_ENABLE_RATE_LIMITING=${enableRateLimiting.toLowerCase() !== 'n' ? 'true' : 'false'}

# Development Settings (disable in production)
EXPO_PUBLIC_ENABLE_DEBUG_MODE=${enableDebugMode.toLowerCase() === 'y' ? 'true' : 'false'}
EXPO_PUBLIC_ENABLE_MOCK_DATA=false
`;

    // Write .env file
    fs.writeFileSync(envPath, envContent);
    
    logStep('✅ Configuration Complete');
    logSuccess('Your .env file has been created successfully!');
    logInfo(`Discourse URL: ${discourseUrl}`);
    logInfo(`HTTPS Only: ${enableHttpsOnly.toLowerCase() !== 'n' ? 'Enabled' : 'Disabled'}`);
    logInfo(`Rate Limiting: ${enableRateLimiting.toLowerCase() !== 'n' ? 'Enabled' : 'Disabled'}`);
    logInfo(`Debug Mode: ${enableDebugMode.toLowerCase() === 'y' ? 'Enabled' : 'Disabled'}`);
    
    logStep('🧪 Next Steps');
    logInfo('1. Start your Expo app:');
    logInfo('   npm start');
    logInfo('');
    logInfo('2. Test the User API Key authentication flow');
    logInfo('   Users will authorize the app through the Discourse web interface');
    logInfo('');
    logInfo('3. Check the profile page to see real Discourse data');

  } catch (error) {
    logError(`Setup failed: ${error.message}`);
  } finally {
    rl.close();
  }
}

// Run the setup
if (require.main === module) {
  setupEnvironment().catch((error) => {
    logError(`Setup failed: ${error.message}`);
    process.exit(1);
  });
}

module.exports = { setupEnvironment }; 