#!/usr/bin/env node

/**
 * Environment Setup Script
 * 
 * This script helps you configure your .env file with your actual Discourse instance details.
 */

const fs = require('fs');
const readline = require('readline');

// Colors for console output
const colors = {
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  reset: '\x1b[0m',
  bold: '\x1b[1m'
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function logStep(step) {
  log(`\n${colors.bold}${step}${colors.reset}`);
}

function logSuccess(message) {
  log(`✅ ${message}`, 'green');
}

function logError(message) {
  log(`❌ ${message}`, 'red');
}

function logWarning(message) {
  log(`⚠️  ${message}`, 'yellow');
}

function logInfo(message) {
  log(`ℹ️  ${message}`, 'blue');
}

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setupEnvironment() {
  log(`${colors.bold}🔧 Discourse Environment Setup${colors.reset}`);
  log('This script will help you configure your .env file with your Discourse instance details.');
  log('');

  try {
    // Check if .env already exists and has content
    const envPath = '.env';
    let existingContent = '';
    
    if (fs.existsSync(envPath)) {
      existingContent = fs.readFileSync(envPath, 'utf8');
      if (existingContent.trim()) {
        logWarning('A .env file already exists with content.');
        const overwrite = await question('Do you want to overwrite it? (y/N): ');
        if (overwrite.toLowerCase() !== 'y' && overwrite.toLowerCase() !== 'yes') {
          logInfo('Setup cancelled. Your existing .env file was preserved.');
          rl.close();
          return;
        }
      }
    }

    logStep('📝 Discourse Instance Configuration');
    
    // Get Discourse URL
    logInfo('Enter your Discourse instance URL:');
    logInfo('Example: https://discourse.example.com');
    const discourseUrl = await question('Discourse URL: ');
    
    if (!discourseUrl || discourseUrl === 'https://your-discourse-instance.com') {
      logError('Please provide a valid Discourse URL.');
      rl.close();
      return;
    }

    // Validate URL format
    try {
      new URL(discourseUrl);
    } catch {
      logError('Invalid URL format. Please provide a valid URL starting with http:// or https://');
      rl.close();
      return;
    }

    // Get API Key
    logStep('🔑 API Credentials');
    logInfo('You need to create an API key in your Discourse admin panel:');
    logInfo('1. Log into your Discourse admin panel');
    logInfo('2. Go to Admin → API → API Keys');
    logInfo('3. Create a new API key with appropriate permissions');
    logInfo('');
    
    const apiKey = await question('API Key: ');
    if (!apiKey || apiKey === 'your_api_key_here') {
      logError('Please provide a valid API key.');
      rl.close();
      return;
    }

    // Get API Username
    const apiUsername = await question('API Username: ');
    if (!apiUsername || apiUsername === 'your_api_username_here') {
      logError('Please provide a valid API username.');
      rl.close();
      return;
    }

    // Security settings
    logStep('🔒 Security Settings');
    logInfo('Configuring security settings...');
    
    const enableHttpsOnly = await question('Enable HTTPS only? (Y/n): ');
    const enableRateLimiting = await question('Enable rate limiting? (Y/n): ');
    const enableDebugMode = await question('Enable debug mode for development? (y/N): ');

    // Generate .env content
    const envContent = `# Discourse API Configuration
# Generated by setup script - ${new Date().toISOString()}

# Your Discourse instance URL (must be HTTPS in production)
EXPO_PUBLIC_DISCOURSE_URL=${discourseUrl}

# Discourse API credentials (create these in your Discourse admin panel)
EXPO_PUBLIC_DISCOURSE_API_KEY=${apiKey}
EXPO_PUBLIC_DISCOURSE_API_USERNAME=${apiUsername}

# Security Settings
EXPO_PUBLIC_ENABLE_HTTPS_ONLY=${enableHttpsOnly.toLowerCase() !== 'n' ? 'true' : 'false'}
EXPO_PUBLIC_ENABLE_CERT_PINNING=false
EXPO_PUBLIC_ENABLE_RATE_LIMITING=${enableRateLimiting.toLowerCase() !== 'n' ? 'true' : 'false'}

# Development Settings (disable in production)
EXPO_PUBLIC_ENABLE_DEBUG_MODE=${enableDebugMode.toLowerCase() === 'y' ? 'true' : 'false'}
EXPO_PUBLIC_ENABLE_MOCK_DATA=false
`;

    // Write .env file
    fs.writeFileSync(envPath, envContent);
    
    logStep('✅ Configuration Complete');
    logSuccess('Your .env file has been created successfully!');
    logInfo(`Discourse URL: ${discourseUrl}`);
    logInfo(`API Username: ${apiUsername}`);
    logInfo(`HTTPS Only: ${enableHttpsOnly.toLowerCase() !== 'n' ? 'Enabled' : 'Disabled'}`);
    logInfo(`Rate Limiting: ${enableRateLimiting.toLowerCase() !== 'n' ? 'Enabled' : 'Disabled'}`);
    logInfo(`Debug Mode: ${enableDebugMode.toLowerCase() === 'y' ? 'Enabled' : 'Disabled'}`);
    
    logStep('🧪 Next Steps');
    logInfo('1. Test your configuration:');
    logInfo('   node scripts/test-auth.js');
    logInfo('');
    logInfo('2. Start your Expo app and test the authentication flow');
    logInfo('');
    logInfo('3. Check the profile page to see real Discourse data');
    
    // Test the configuration immediately
    logStep('🔍 Testing Configuration');
    logInfo('Running authentication test...');
    
    // Set environment variables for the test
    const envVars = envContent.split('\n')
      .filter(line => line.includes('='))
      .reduce((acc, line) => {
        const [key, value] = line.split('=');
        if (key && value) {
          acc[key.trim()] = value.trim();
        }
        return acc;
      }, {});
    
    // Set environment variables
    Object.assign(process.env, envVars);
    
    // Import and run the test
    try {
      const { testDiscourseConnection, testApiAuthentication } = require('./test-auth.js');
      
      const connectionOk = await testDiscourseConnection();
      if (connectionOk) {
        const authOk = await testApiAuthentication();
        if (authOk) {
          logSuccess('🎉 Configuration test passed! Your Discourse setup is working correctly.');
        } else {
          logWarning('⚠️  Connection works but API authentication failed. Check your API credentials.');
        }
      } else {
        logError('❌ Connection test failed. Please check your Discourse URL.');
      }
    } catch (error) {
      logError(`Test failed: ${error.message}`);
    }

  } catch (error) {
    logError(`Setup failed: ${error.message}`);
  } finally {
    rl.close();
  }
}

// Run the setup
if (require.main === module) {
  setupEnvironment().catch((error) => {
    logError(`Setup failed: ${error.message}`);
    process.exit(1);
  });
}

module.exports = { setupEnvironment }; 